id: PD7D5095D
initial_creation_type: input
source_metadata:
  title: Ngawang Tendar Series
  language: bo
  description: 'Texts by and about the renowned Mongolian scholar Ngawang Tendar (ngag
    dbang bstan dar, 1759/1751–1831):'
  volume:
    17cea1be6d154ad08d61b507267baf58:
      title: On Literary Composition
      parent: Literary Theory
created_at: '2022-03-01T01:00:08.885428'
last_modified_at: '2022-03-01T01:00:08.885431'
